#+OPTIONS: tex:t
#+STARTUP: latexpreview

* Tema 1 :noexport:
** Ejercicio 6
*** a) Hallar las raíces
Para hallar el término $x_{n+1}$ hay que sacar las raíces del polinomio:

$$p(x) = f(x_n) + f'(x_n)(x - x_n) + \frac12f''(x_n)(x-x_n)^2$$

Por tanto:

$$x_{n+1} = x_n + \frac{-f'(x_n) \pm \sqrt{f'(x_n)^2 - 2f(x_n)f''(x_n)}}{f''(x_n)}$$

*** b) ¿Qué raíz debemos escoger?

Debemos llegar a un punto tal que $f(x^\ast) = 0$. Este será un punto fijo, es decir:

$$x^\ast = x^\ast + \frac{-f'(x^\ast) \pm \sqrt{f'(x^\ast)^2 - 2f(x^\ast)f''(x^\ast)}}{f''(x^\ast)}$$

Es decir, el término de la derecha debe anularse. Simplificando y haciendo $f(x^\ast) = 0$ tenemos que:

$$-f'(x^\ast) \pm \sqrt{f'(x^\ast)^2} = 0$$

Por tanto debemos escoger la raíz con símbolo $+$.

*** c) Comprobación del método

Si multiplicamos por el conjugado la expresión original:

$$x_{n+1} = x_n - \frac{f'(x_n) - \sqrt{f'(x_n)^2 - 2f(x_n)f''(x_n)}}{f''(x_n)} \cdot \frac{f'(x_n) + \sqrt{f'(x_n)^2 - 2f(x_n)f''(x_n)}}{f'(x_n) + \sqrt{f'(x_n)^2 - 2f(x_n)f''(x_n)}}$$


Simplificando:

$$x_{n+1} = x_n - \frac{f'(x_n)^2 - f'(x_n)^2 + 2f(x_n)f''(x_n)}{(f'(x_n) + \sqrt{f'(x_n)^2 - 2f(x_n)f''(x_n)})f''(x_n)}$$

Reordenando términos y sacando $f'(x_n)^2$:


$$x_{n+1} = x_n - \frac{2}{1 + \sqrt{1 - 2\frac{f(x_n)f''(x_n)}{f'(x_n)^2}}}\frac{f(x_n)}{f'(x_n)}$$

*** d)

Hecho en Maxima. No converge.

*** e)

Sea $x^\ast$ el punto fijo de $f$. Por el teorema de Taylor existe $\xi$ en el menor intervalo abierto que contiene a $x_k$ y $x^\ast$ tal que:

$$0 = f(x^\ast) = f(x_k) + f'(x_k)(x^\ast - x_k) + \frac12f''(x_k)(x^\ast - x_k)^2 + \frac16f'''(\xi)(x^\ast - x_k)^3$$

Además, por cómo se ha elegido $x_{k+1}$:

$$0 = f(x_k)+ f'(x_k)(x_{k+1}-x_k) + \frac12f''(x_k)(x_{k+1}-x_k)^2$$

Restando una expresión a otra:

$$0 = f'(x_k)(x^\ast - x_{k+1}) + \frac12f''(x_k)(x^\ast - x_{k+1})(x^\ast + x_{k+1} - 2x_k) + \frac16f'''(\xi)(x^\ast - x_k)^3$$

Sacamos factor común y despejamos:


$$\left(f'(x_k) + \frac12f''(x_k)(x^\ast + x_{k+1} - 2x_k)\right)(x^\ast - x_{k+1}) = \frac16f'''(\xi)(x_k - x^\ast)^3$$

Tomamos valor absoluto y tenemos que:

$$|x^\ast - x_{k+1}| = \frac16\frac{|f'''(\xi)|}{\left|f'(x_k) + \frac12f''(x_k)(x^\ast + x_{k+1} - 2x_k)\right|}|x^\ast - x_k|^3$$

Sea $f \in C^3([x^\ast - \delta_1, x^\ast + \delta_1])$ para algún $\delta_1 > 0$. Como $f'(x^\ast) \neq 0$, por el lema de conservación del signo $\exists \delta_2$ con $0 < \delta_2 \leq \delta_1$ tal que, siendo $I_2 = [x^\ast - \delta_2, x^\ast + \delta_2]$:

$$\min_{x \in I_2} |f'(x)| > 0$$

Sea $\displaystyle M_{i, \delta} = \max_{x \in [x^\ast - \delta, x^\ast + \delta]} |f^{(i)}(x)|$, que existe para todo $i$ menor que $4$ y todo $\delta$ menor o igual que $\delta_2$ por el teorema de Weierstrass y porque $f \in C^3(I_2)$. Sea $m_{i, \delta}$ la expresión con el mínimo, que en el caso anterior existe, por lo que podemos llamar $m_{1, \delta_2}$ a la cota inferior anterior.

Tomamos $\delta$ con $0 < \delta \leq \delta_2$ tal que $\delta M_{2, \delta_2} < \frac 2 3 m_{1, \delta_2}$ y $M_{2, \delta_2} \left( 2 \frac {M_{0, \delta}}{m_{1, \delta_2}} \right) < m_{1, \delta_2}$. La segunda igualdad puede conseguirse porque $f(x)$ tiende a $0$ cuando $x$ tiende a $x^\ast$. Entonces, tomando $x_k \in I := [x^\ast - \delta, x^\ast + \delta]$ y usando la definición de $x_{k+1}$:

$$ \frac{|f'''(\xi)|}{\left|f'(x_k) + \frac12f''(x_k)(x^\ast + x_{k+1} - 2x_k)\right|} \leq \frac{M_{3, \delta}}{m_{1, \delta} - \frac12 M_{2, \delta} |\underbrace{x^\ast - x_k}_{\leq \delta} + x_{k+1} - x_k|} $$
$$ \leq \frac{M_{3, \delta}}{m_{1, \delta_2} - \frac12 M_{2, \delta_2} \big(\delta + |\frac 2 {\underbrace{1 + \sqrt{...}}_{\leq 1}} \frac {M_{0, \delta}}{m_{1, \delta_2}}| \big)} \leq \frac{M_{3, \delta}}{m_{1, \delta_2} - \frac13 m_{1, \delta_2} - \frac12 m_{1, \delta_2}} = \frac{6 M_{3, \delta}}{m_{1, \delta_2}}$$

Por ello, sea $K = \frac{M_{3, \delta}}{m_{1, \delta_2}}$, podemos acotar la expresión que queríamos:

$$|x^\ast - x_{k+1}| \leq K|x^\ast - x_k|^3$$

Dando así orden de convergencia 3.

** Ejercicio 9
*** $x_{n+1} = 1 - \log x_n$
Esta sucesión converge a un punto fijo de $1 - \log x_n$, es decir, un punto en el que:

$$1 - \log x = x$$

por lo que no sirve para resolver el problema.

El *resto de sucesiones* si convergen lo hacen a un punto tal que $1 - \log x = 0$.

*** $x_{n+1} = x_n + 1 - \log x_n$
Consideramos la aplicación $g(x) = x + 1 - \log x$:

Vemos que $|g'| < 1$ en $(0,+\infty)$ por lo que la aplicación es contractiva.

Además, $g([2,3]) \subseteq [2,3]$

*** $x_{n+1} = x_n - (1 - \log x_n)$ 

Consideramos la aplicación $g(x) = x - (1 - \log x)$:

Vemos que $|g'| > 1$ en $(0,+\infty)$ por lo que la aplicación *no* es contractiva.
Por tanto *no* podemos aplicar el teorema del punto fijo.

*** $x_{n+1} = x_n + (1 - \log x_n)/3$ 
Consideramos la aplicación $g(x) = x + (1 - \log x)/3$:

Vemos que $|g'| < 1$ en $(0,+\infty)$ por lo que la aplicación es contractiva.

Además $g([2,3]) \subseteq [2,3]$
** Ejercicio 18
*** a) Hallar $D$ y $g$ para el método
Sea $D = [0,1]^2$. Podemos tomar como $g = g_1 \times g_2$:

$$g_1(x,y) = \frac{1}{\sqrt{5}}y = x \iff 5x^2 - y^2 = 0$$
$$g_2(x,y) = \frac14(\sin x + \cos y) = y \iff y - 0.25(\sin x +\cos y) = 0$$

Tenemos que $g_1,g_2 \geq 0$ en $D$. Además, claramente: $\max g_1 = \frac1{\sqrt{5}} < 1$ y $\max g_2 \leq \frac12$. Así, $g(D) \subseteq D$.
Por otra parte, $g \in C^1(D)$ y:

$$J g(x) = \left(\begin{matrix}0 & \frac{1}{\sqrt{5}} \\ \frac{\cos x}{4} & \frac{-\sin y}{4} \end{matrix}\right)$$

Y por tanto $||J g(x)||_\infty = \max_{x,y \in D} \{ \frac{1}{\sqrt{5}}, \frac14(|\cos x| + |\sin y|) \} = \frac12 < 1$, por lo que la aplicación es contractiva en $D$.

Así, por el teorema de convergencia global, existe $x^\ast \in D$ tal que $g(x^\ast) = x^\ast$. Además el teorema garantiza la convergencia a ese punto mediante iteración funcional.

* Tema 2
** Ejercicio 9
*** a)
Si llamamos los nodos $x_i, x_j, x_k$ tenemos que:

$$l_i'(x) = \frac{2x - x_j - x_k}{(x_i -x_k)(x_i - x_j)}$$

Es decir:

- $l_0'(x) = \frac{2x - 4h}{3h^2}$, por lo que $l_0'(2h) = 0$
- $l_1'(x) = \frac{2x - 3h}{-2h^2}$, por lo que $l_1'(2h) = \frac{-1}{2h}$
- $l_2'(x) = \frac{2x - h}{6h^2}$, por lo que $l_2'(2h) = \frac{1}{2h}$

Por tanto la fórmula de derivación numérica queda:

$$\operatorname{FDN}(f) = \sum f(x_i)l_i(x) = \frac{f(3h) - f(h)}{2h}$$

*** b)

Desarrollamos el polinomio de Taylor centrado en $2h$:

$$f(x) = f(2h) + f'(2h)(x-2h) + \frac12 f''(2h)(x-2h)^2 + \frac16 f'''(\xi)(x-2h)^3$$

Evaluando en $3h$ y en $h$ tenemos, para $h < \xi_2 < 2h < \xi_1 < 3h$:

$$f(3h) = f(2h) + hf'(2h) + \frac12 h^2 f''(2h) + \frac16 h^3 f'''(\xi_1)$$
$$f(h) = f(2h) - hf'(2h) + \frac12 h^2 f''(2h) - \frac16 h^3  f'''(\xi_2)$$

La diferencia vale:

$$f(3h) - f(h) = 2hf'(2h) + \frac16 h^3 (f'''(\xi_1) + f'''(\xi_2))$$

Si $f \in \mathcal{C}^3$ por el teorema de los valores intermedios tenemos que existe un $h < \xi < 3h$ tal que:

$$f(3h) - f(h) = 2hf'(2h) + \frac13 h^3 f'''(\xi)$$

Por tanto:

$$\operatorname{ED}(f) = f'(2h) - \operatorname{FDN}(f) = f'(2h) - \frac{f(3h)-f(h)}{2h} = - \frac{h^2}{6} f'''(\xi)$$

** Ejercicio 13
*** Deduce las expresiones de las fórmulas de Newton-Cotes abiertas con $n = 1$ y $n = 2$ y obtén la expresión del error de dichas fórmulas

Las fórmulas se obtienen de:

$$\operatorname{FC}_n(f) = \sum_{i=0}^{n}\left(\int_0^2 l_i\right)f\left(a + (i+1)\frac{b-a}{n+2}\right)$$

Para calcular las integrales de los polinomios de la base de Lagrange utilizamos el cambio de variable que las transforma en integrales estándar.

En el caso de *n = 1* tenemos:

#+TODO

El error tiene la expresión, para cierto $\xi \in [0,2]$:

$$\operatorname{EC}_1(f) = \frac{h^{1+2}f^{1+1)}(\xi)}{(1+1)!}\int_{-1}^{1+1} y(y-1) \; dy = \frac{3h^3}{4}f^{2)}(\xi)$$

En el caso de *n = 2* tenemos:
  
#+TODO

El error tiene la expresión, para cierto $\xi \in [0,2]$:

$$\operatorname{EC}_2(f) = \frac{h^{2+3}f^{2+2)}(\xi)}{(2+2)!}\int_{-1}^{2+1} y^2(y-1)(y-2) \; dy = \frac{14h^5}{45}f^{4)}(\xi)$$

*** Calcula utilizando las fórmulas obtenidas en el apartado anterior las aproximaciones de $\int_0^2x^3 - 2x^2 +1 \; dx$

Basta aplicar las fórmulas utilizadas anteriormente, con $h = 2/(n+2)$, $a = 0$, $b = 2$.

$$\operatorname{FNC}_1(f) = \frac{3h}{2}[f(a+h) + f(b-h)] = \frac29 = 0.\bar{2} $$
$$\operatorname{FNC}_2(f) = \frac{4h}{3}\left[2f(a+h) -f\left(\frac{a+b}{2}\right)+ 2f(b-h)\right] = \frac23$$

*** Compara los errores reales con los errores teóricos cometidos
Podemos calcular el valor exacto de la integral obteniendo una primitiva:

$$\int_0^2x^3 - 2x^2 +1 \; dx = \left[\frac14 x^4 - \frac23 x^3 + x \right]_0^2 = 4-5\frac{1}{3} + 2 = \frac23$$

Comparamos con las cotas del error que nos proporciona la expresión del error de las fórmulas:

$$|E_1|(f) = \frac49 \quad |E_1(f)| = \frac{3h^3}{4}|f''(\xi)| = |\frac89(6\xi-4)| \leq \frac89(12-4) = \frac{16}{9} $$

$$|E_2|(f) = 0 \quad |E_2(f)| = \frac{14h^5}{45}|f^4)(\xi)| = 0$$
